name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
# python
  - mpi4py=3.1.3
  - numpy=1.23.1
  - python=3.10
  - scipy=1.10

# jupyter
  - ipywidgets=8.0.1
  - itkwidgets=0.32.6
  - jupyter=1.0
  - jupyter_contrib_nbextensions=0.7
  - jupyter_nbextensions_configurator=0.6
  - jupyterlab=3.6
  - notebook=6.4.12

# computing stuff
  - fenics=2019.1.0
  - gmsh=4.11
  - meshio=5.3
  - vtk=9.2

# plotting stuff
  - matplotlib=3.7
  - gnuplot=5.4

  - pip=22.2.2
  - pip:
  # computing stuff
    - gmsh==4.11
    - meshio==5.3

  # mechanics stuff
    - dolfin_mech==2024.7.24
    - dolfin-warp==2024.10.20
    - dolfin_estim==2024.7.25.post2
    

variables:
  - CPATH: /srv/conda/envs/notebook/include/vtk-9.2
  - expart=2.5
  
